### PR TITLE
Themes: Add recent versions

### PR DESCRIPTION
**Pull request by adrogon**
Hello FusionAuth, please find a bunch of commits containing the versions of your theme published since you last committed here.

Each commit was created by extracting the theme available from [Docker Hub](https://hub.docker.com/r/fusionauth/fusionauth-app/tags) using the `download.sh` tool you provide [here](https://github.com/FusionAuth/fusionauth-theme-helper).

Only versions containing theme changes are listed here; unlisted therefore did not contain theme changes.

Please notice the latest published version (1.45.1) already has some discrepancy with the provided Docker image, which explains the first commit.

Why isn't this repository maintained? Are these themes available somewhere else then? Or would you like it to be maintained going forward? Since we have to maintain them on our side when upgrading anyway, publishing the theme here as well is not much work for us, so up to you to decide what you would like here.

Thank you :)

### CODE REVIEW

**Comment by mooreds** [comment]
@adrogon This was a hackfest project that never got fully turned into a production ready process. 

Do you think this repository has value for users? If so, how would you use it?

**Comment by adrogon** [comment]
Hi @mooreds, thank you for your reply.

For the exact reason you wrote on the project:
> review the differences between the versions

As per your [Upgrade documentation](https://fusionauth.io/docs/operate/deploy/upgrade), each time there's a new version of FusionAuth, we currently need to find out whether the themes have changed, and if they have, whether these changes impact our custom themes or not.

If the new version's theme was published as part of the release process, we'd have this information at glance.
And we could skip the "Templates" part of the Upgrade process entirely if no change happened, and almost entirely even when there are some.

So valuable you'd even be able to add these changes to the release changelog:
> Themes have changed, new files were added, please find the exhaustive list of changes [here](https://github.com/FusionAuth/fusionauth-theme-history/pull/1/commits/ef3ef94166a4d9182eaa7580bfe8a7433e7ff3a6).

**Comment by mooreds** [comment]
Thanks for the feedback. I'll think about getting this production ready. Really appreciate the feedback!

**Comment by robotdan** [comment]
@mooreds maybe you should update the `README.md` to indicate this is not maintained and is just a prototype or something like that?

**Comment by mooreds** [comment]
Great call, just updated it @robotdan

**Pull request merged**
